### PR TITLE
Use clap::helpers::PluginProxy

### PR DESCRIPTION
**Pull request by Trinitou**
Haven't done a build test on my machine but in theory it should work :D

Before merging
- [x] wait for `clap-helpers` PR https://github.com/free-audio/clap-helpers/pull/27 before merging as it contains a build fix.
- [x] After doing that update `clap-helpers` submodule again

### CODE REVIEW

**Comment by Trinitou** [comment]
Better wait for `clap-helpers` PR https://github.com/free-audio/clap-helpers/pull/27 before merging as it contains a build fix.
If so, update `clap-helpers` submodule before merging as well

**Comment by abique** [comment]
Following up with the previous merges, I had to do a bunch of compilation fixes.
Sorry for the conflicts, but that shouldn't be too hard to fix :+1:

**Comment by Trinitou** [comment]
> Following up with the previous merges, I had to do a bunch of compilation fixes. Sorry for the conflicts, but that shouldn't be too hard to fix 👍

Actually I already pre-calculated some conflicts where merging the `clap::helpers::Host` would touch the same lines of code.

So I hope this time I catched all potential errors when resolving the conflicts. Also I tried to copy your template handling from the Host over to the PluginProxy as well.
Again, I havent't built the project (I should I know 😅). Thank you for taking the time to wipe out all those build errors I introduced with the `clap::helpers::Host`, @abique!

**Comment by abique** [comment]
Thank you for this work! :+1:

**Pull request merged**
