### PR TITLE
Add a test mode where clap-host ignores cookies

### PR DESCRIPTION
**Pull request by baconpaul**
Add a test mode wher clap-host sets all param cookies to nullptr.

### CODE REVIEW

**Comment by abique** [comment]
The `getenv()` approach isn't right, it'd be an hidden feature, best would be a toggle in the menu maybe?

**Comment by baconpaul** [comment]
Ok well I don’t know how to do thst!

can we collaborate here and you make a menu item which toggles thst state global? These are all the correct intercept points

**Comment by baconpaul** [comment]
oh i think i see. hold on

**Comment by baconpaul** [comment]
oh no i don't. now I'm in QT land. Ugh. I don't see a place to put it

Anyway, the ifs are correct; i just don't know how to add a settings panel to set the flag to true or false. I'll leave this here for now.

**Comment by abique** [comment]
I've implemented the feature the way I wanted.
There's now a tweak dialog where we can add more settings in the future.

**Comment by baconpaul** [comment]
Awesome thanks @abique !

Between this and the validator changes we can test this well now.

**Pull request closed without merging**
